config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :hotels do
    resources :reservations
  end

  get "/search_results", to: "reservations#search_results"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reservations#search"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :hotel

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :hotel_id, presence: true
  validates :arrival_date, presence: true
  validates :departure_date, presence: true
  validates :no_of_rooms, presence: true
  validate :arrival_not_in_the_past
  validate :arrival_before_departure
  validate :hotel_not_full

  private

  def arrival_before_departure
    if arrival_date.present? && departure_date.present? && arrival_date > departure_date
      errors.add(:arrival_date, "can't be after departure date")
    end
  end

  def arrival_not_in_the_past
    if arrival_date.present? && arrival_date < Date.today
      errors.add(:arrival_date, "can't be in the past")
    end
  end

  def hotel_not_full
    puts "Starting hotel_not_full validation"
    if hotel_id.present?
      puts "Checking if hotel is full"
      if no_of_rooms > hotel.available_rooms(arrival_date, departure_date)
        errors.add(:no_of_rooms, "can't be greater than available rooms")
      end
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    # Filters reservations by hotel_id if the hotel_id parameter is present.
    # it is in the /hotels/:hotel_id/reservations route.
    if !params[:hotel_id].blank?
      @reservations = Hotel.find(params[:hotel_id]).reservations
    else
      @reservations = Reservation.all
    end
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    render :search
  end

  def book
    render :book
  end

  def search_results
    if params[:city].blank? || params[:arrival_date].blank? || params[:departure_date].blank? || params[:no_of_rooms].blank? || params[:max_price].blank?
      redirect_to root_url, notice: "Please fill in all the fields"
      return
    end
    if params[:arrival_date] > params[:departure_date]
      redirect_to root_url, notice: "Arrival date must be before departure date"
      return
    end
    if params[:no_of_rooms].to_i <= 0
      redirect_to root_url, notice: "Number of rooms must be greater than 0"
      return
    end
    if params[:max_price].to_i <= 0
      redirect_to root_url, notice: "Max price must be greater than 0"
      return
    end
    if Date.parse(params[:arrival_date]) < Date.today
      redirect_to root_url, notice: "Arrival date cannot be in the past"
      return
    end
    puts "Searching for hotels in #{params[:city]}"
    puts params
    # Convert numbered params to numbers
    params[:no_of_rooms] = params[:no_of_rooms].to_i
    params[:max_price] = params[:max_price].to_i
    # Filter hotels by city
    @hotels = Hotel.where("LOWER(city) = ?", params[:city].downcase)
    # Find hotels that are available between the arrival and departure dates
    if params[:arrival_date] && params[:departure_date]
      @available_hotels = []
      @hotels.each do |hotel|
        # Add the hotel to available_hotels if it has enough rooms and the max price is less than hotel.room_price
        if params[:no_of_rooms] <= hotel.available_rooms(params[:arrival_date], params[:departure_date]) && params[:max_price] >= hotel.room_price
          @available_hotels << hotel
        end
      end
      @hotels = @available_hotels
    end
    render :search_results
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:first_name, :last_name, :phone, :email, :hotel_id, :arrival_date, :departure_date, :no_of_rooms)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, class: "contents") do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <% if !params[:hotel_id].blank? %>
    <%= form.hidden_field :hotel_id, value: params[:hotel_id] %>
  <% else %>
    <div class="my-5">
      <%= form.label :hotel_id %>
      <%= form.text_field :hotel_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  <% end %>

  <% if !params[:arrival_date.blank?] %>
    <%= form.hidden_field :arrival_date, value: params[:arrival_date] %>
  <% else %>
    <div class="my-5">
      <%= form.label :arrival_date %>
      <%= form.date_field :arrival_date,
                          class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
                          value: params[:arrival_date] %>
    </div>
  <% end %>

  <% if !params[:departure_date.blank?] %>
    <%= form.hidden_field :departure_date, value: params[:departure_date] %>
  <% else %>
    <div class="my-5">
      <%= form.label :departure_date %>
      <%= form.date_field :departure_date,
                          class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
                          value: params[:departure_date] %>
    </div>
  <% end %>

  <% if !params[:no_of_rooms.blank?] %>
    <%= form.hidden_field :no_of_rooms, value: params[:no_of_rooms] %>
  <% else %>
    <div class="my-5">
      <%= form.label :no_of_rooms %>
      <%= form.number_field :no_of_rooms,
                            class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
                            value: params[:no_of_rooms] %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= reservation.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= reservation.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= reservation.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= reservation.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Hotel:</strong>
    <%= reservation.hotel_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Arrival date:</strong>
    <%= reservation.arrival_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Departure date:</strong>
    <%= reservation.departure_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">No of rooms:</strong>
    <%= reservation.no_of_rooms %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this reservation", reservation, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this reservation', edit_reservation_path(reservation), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/reservations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing reservation</h1>

  <%= render "form", reservation: @reservation %>

  <%= link_to "Show this reservation", @reservation, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to reservations", reservations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/reservations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Reservations</h1>
    <%= link_to 'New reservation', new_reservation_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="reservations" class="min-w-full">
    <%= render @reservations %>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New reservation</h1>

  <%= render "form", reservation: @reservation %>

  <%= link_to 'Back to reservations', reservations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/reservations/search.html.erb
<div>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
</div>
<div>
  <%= link_to "Hotels", hotels_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>
<div class="flex flex-col items-center mx-auto space-y-2">
  <h1 class="font-bold text-2xl">Find a Hotel Room</h1>
  <form action="/search_results" method="get" class="flex flex-col space-y-2">
    <div class="flex flex-col">
      <label for="city">City</label>
      <input type="text" id="city" name="city">
    </div>
    <div class="flex flex-col">
      <label for="arrival_date">Arrival Date</label>
      <input type="date" id="arrival_date" name="arrival_date" value="<%= Date.today %>">
    </div>
    <div class="flex flex-col">
      <label for="departure_date">Departure Date</label>
      <input type="date" id="departure_date" name="departure_date" value="<%= Date.today + 7 %>">
    </div>
    <div class="flex flex-col">
      <label for="no_of_rooms">Number of Rooms</label>
      <input type="number" id="no_of_rooms" name="no_of_rooms" value="1">
    </div>
    <div class="flex flex-col">
      <label for="max_price">Max price</label>
      <input type="number" id="max_price" name="max_price" value="1000">
    </div>
    <div class="flex flex-col bg-blue-600 rounded-lg text-white">
      <input type="submit" value="Search" class="px-3 py-3 cursor-pointer">
    </div>
  </form>
</div>

app/views/reservations/search_results.html.erb
<div>
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= link_to "Search again", root_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
</div>

<div class="flex-col justify-between items-center mx-auto">
  <h1 class="text-2xl font-bold mb-3 text-center">Search results</h1>
  <div id="search_results" class="min-w-full flex space-x-4 space-y-4">
    <% @hotels.each do |hotel| %>
      <div class="bg-gray-100 rounded-lg px-4 py-4">
        <p class="my-5">
          <strong class="block font-medium mb-1">Name:</strong>
          <%= hotel.name %>
        </p>

        <p class="my-5">
          <strong class="block font-medium mb-1">City:</strong>
          <%= hotel.city %>
        </p>

        <p class="my-5">
          <strong class="block font-medium mb-1">Number of rooms:</strong>
          <%= hotel.number_of_rooms %>
        </p>

        <p class="my-5">
          <strong class="block font-medium mb-1">Room price:</strong>
          <%= hotel.room_price %>
        </p>

        <%= link_to "Book this hotel", new_reservation_path(
          hotel_id: hotel.id,
          arrival_date: params[:arrival_date],
          departure_date: params[:departure_date],
          no_of_rooms: params[:no_of_rooms],
        ), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @reservation %>

    <%= link_to 'Edit this reservation', edit_reservation_path(@reservation), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this reservation', reservation_path(@reservation), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to reservations', reservations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>