config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :hotels do
    resources :reservations
  end

  get "/search_results", to: "reservations#search_results"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reservations#search"
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :reservations, dependent: :destroy

  validates :name, presence: true
  validates :city, presence: true
  validates :number_of_rooms, presence: true
  validates :room_price, presence: true

  # Find amount of available rooms between the arrival and departure dates
  def available_rooms(arrival_date, departure_date)
    puts "Searching for available rooms between #{arrival_date} and #{departure_date}"
    reservations = 0
    begin
      if arrival_date.is_a?(String)
        arrival_date = Date.parse(arrival_date) # convert arrival_date to date object
      end
      if departure_date.is_a?(String)
        departure_date = Date.parse(departure_date) # convert departure_date to date object
      end
      self.reservations.each do |reservation|
        puts "Checking reservation #{reservation.id}"
        if reservation.arrival_date < departure_date && reservation.departure_date > arrival_date
          puts "Reservation #{reservation.id} is in the way!"
          reservations += reservation.no_of_rooms
        end
      end
      self.number_of_rooms - reservations
    rescue ArgumentError # handle invalid date error
      0
    end
  end

  # Get the amount of occupied rooms on this given day
  def occupied_rooms
    reservations = 0
    self.reservations.each do |reservation|
      if reservation.arrival_date <= Date.today && reservation.departure_date >= Date.today
        reservations += reservation.no_of_rooms
      end
    end
    reservations
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reservations
    @hotel = Hotel.find(params[:id])
    @reservations = @hotel.reservations
    redirect_to hotel_reservations_path(@hotel)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :city, :number_of_rooms, :room_price)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel, class: "contents") do |form| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :city %>
    <%= form.text_field :city, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :number_of_rooms %>
    <%= form.number_field :number_of_rooms, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :room_price %>
    <%= form.text_field :room_price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= hotel.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= hotel.city %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Number of rooms:</strong>
    <%= hotel.number_of_rooms %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Occupied rooms today:</strong>
    <%= hotel.occupied_rooms %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Reservations:</strong>
    <%= hotel.reservations.size %>

  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Room price:</strong>
    <%= hotel.room_price %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this hotel", hotel, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this hotel', edit_hotel_path(hotel), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Show reservations', hotel_reservations_path(hotel), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/hotels/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing hotel</h1>

  <%= render "form", hotel: @hotel %>

  <%= link_to "Show this hotel", @hotel, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to hotels", hotels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/hotels/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Hotels</h1>
    <%= link_to 'New hotel', new_hotel_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="hotels" class="min-w-full">
    <%= render @hotels %>
  </div>
</div>

app/views/hotels/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New hotel</h1>

  <%= render "form", hotel: @hotel %>

  <%= link_to 'Back to hotels', hotels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/hotels/reservations.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Reservations</h1>
    <%= link_to 'New reservation', new_reservation_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="reservations" class="min-w-full">
    <%= render @reservations %>
  </div>
</div>

app/views/hotels/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @hotel %>

    <%= link_to 'Show reservations', hotel_reservations_path(@hotel), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this hotel', edit_hotel_path(@hotel), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this hotel', hotel_path(@hotel), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to hotels', hotels_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>